service: escape-booth

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: ap-southeast-2
  environment:
    ENVIRONMENT: ${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
      Resource:
        - { "Fn::Join" : [":", ["arn:aws:dynamodb:${self:custom.region}", { "Ref" : "AWS::AccountId" }, "table/${self:service}-${self:custom.stage}-users" ] ]  }
        - { "Fn::Join" : [":", ["arn:aws:dynamodb:${self:custom.region}", { "Ref" : "AWS::AccountId" }, "table/${self:service}-${self:custom.stage}-leaderboard" ] ]  }

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}

functions:
  userCreate:
    handler: src/user.create
    events:
      - http:
          path: user
          method: post
  leaderboardCreate:
    handler: src/leaderboard.create
    events:
      - http:
          path: leaderboard
          method: post
  leaderboardUpdate:
    handler: src/leaderboard.update
    events:
      - http:
          path: leaderboard
          method: put



# you can add CloudFormation resource templates here
resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "${self:service}-${self:custom.stage}-users"
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    Leaderboard:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "${self:service}-${self:custom.stage}-leaderboard"
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
